using LightInject;
using LinqToSqlAttributesCommon.Container;
using LinqToSqlAttributesCommon.Interfaces;
using LinqToSqlAttributesReplacer.DocumentEditing;
using LinqToSqlAttributesReplacer.DocumentEditing.Factories;
using LinqToSqlAttributesReplacer.DocumentEditing.Factories.PropertyAttributeConverters;

namespace LinqToSqlAttributesReplacer.Configuration
{
    public class ContainerConfigurator : ContainerConfiguratorBase
    {
        public override void Configure(ServiceContainer container)
        {
            base.Configure(container);

            container.Register<IDocumentProcessor, DocumentProcessor>();

            container.Register<IDocumentEditingCommandsCompositeFactory, DocumentEditingCommandsCompositeFactory>();
            container.Register<IDocumentEditingConcreteFactory, NamespaceReplacementCommandFactory>(typeof(NamespaceReplacementCommandFactory).ToString());
            container.Register<IDocumentEditingConcreteFactory, TableAttributesReplacementCommandFactory>(typeof(TableAttributesReplacementCommandFactory).ToString());
            container.Register<IDocumentEditingConcreteFactory, PropertyAttributesReplacementCommandFactory>(typeof(PropertyAttributesReplacementCommandFactory).ToString());

            container.Register<IAttributeParameterConverter, NameAndTypeAttributeParameterConverter>(typeof(NameAndTypeAttributeParameterConverter).ToString());
            container.Register<IAttributeParameterConverter, PrimaryKeyAttributeParameterConverter>(typeof(PrimaryKeyAttributeParameterConverter).ToString());
            container.Register<IAttributeParameterConverter, CanBeNullAttributeParameterConverter>(typeof(CanBeNullAttributeParameterConverter).ToString());
            container.Register<IAttributeParameterConverter, AutogeneratedAttributeParameterConverter>(typeof(AutogeneratedAttributeParameterConverter).ToString());
            container.Register<IAttributeParameterConverter, UpdateCheckAttributeParameterConverter>(typeof(UpdateCheckAttributeParameterConverter).ToString());
            //TODO: Implement (Right)
            //container.Register<IAttributeParameterConverter, DiscriminatorAttributeParameterConverter>(typeof(DiscriminatorAttributeParameterConverter).ToString());

            container.Register<IDocumentWriter, ConsoleDocumentWriter>();
        }
    }
}