using LinqToSqlAttributesCommon.Extensions;
using LinqToSqlAttributesCommon.Helpers;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LinqToSqlAttributesReplacer.DocumentEditing.Factories.PropertyAttributeConverters
{
    public class AutogeneratedAttributeParameterConverter : IAttributeParameterConverter
    {
        private const string generateComputed = "DatabaseGenerationOption.Computed";
        private const string generateIdentity = "DatabaseGenerationOption.Identity";
        private const string generateNone = "DatabaseGenerationOption.None";

        public AttributeSyntax Convert(AttributeSyntax attribute)
        {
            var canBeNull = attribute
                .FindArgument(AttributeArgumentName.ColumenIsAutoGenearted)
                ?.GetBoolValue();

            return canBeNull == false
                ? CreateReplacement()
                : null;
        }

        private static AttributeSyntax CreateReplacement()
        {
            var columnNameAttribute = SyntaxFactory.AttributeArgumentList(
                SyntaxFactory.SeparatedList(new[] {
                    SyntaxFactory.AttributeArgument(
                        SyntaxFactory.LiteralExpression(SyntaxKind.NumericLiteralExpression,
                            SyntaxFactory.Literal(generateIdentity)))}
                    ));

            return SyntaxFactory.Attribute(SyntaxFactory.IdentifierName(AttributeName.EntityDbGenerated), columnNameAttribute);
        }
    }
}